accountApi/accountApi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    # REST FRAMEWORK URLS
    path('api/user/', include('user.api.urls', 'user_api')),
    path('api/account/', include('account.api.urls', 'account_api')),
    path('api/transaction/', include('transaction.api.urls', 'transaction_api')),
    path('', include('adminView.urls')),
]

accountApi/adminView/urls.py
from . import views
from django.urls import path

app_name = 'adminView'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.csvReport, name='csv'),
    path('detail/', views.detail, name='detail'),
]

accountApi/adminView/models.py
from django.db import models

# Create your models here.

accountApi/adminView/views.py
from django.shortcuts import render
from account.models import Account
from user.models import User
from transaction.models import Transaction

import csv
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'adminView/index.html')

def detail(request):
    pk = request.POST['userId']
    user = User.objects.get(id=pk)
    accounts = Account.objects.filter(user=user.id)
    transactions = Transaction.objects.filter(user=user)

    context = {
        'user' : user,
        'accounts': accounts,
        'transactions' : transactions
    }
    return render(request, 'adminView/detail.html', context)

def csvReport(request, pk):
    headerAccount = ['ID', 'USER ID', 'TYPE', 'AMOUNT']
    headerTransaction = ['ID', 'USER ID', 'ACTION', 'AMOUNT']
    response = HttpResponse('text/csv')
    response['Content-Disposition'] = 'attachment; filename=report.csv'
    print(pk)
    user = User.objects.get(id=pk)
    accounts = Account.objects.filter(user=user.id)
    
    writer = csv.writer(response)
    writer.writerow(headerAccount)

    for account in accounts:
        writer.writerow([account.id, account.user,  account.type, account.amount])
    
    transactions = Transaction.objects.filter(user=user)
    writer.writerow([])
    writer.writerow([])

    writer.writerow(headerTransaction)

    for transaction in transactions:
        writer.writerow([transaction.id, transaction.user, transaction.action, transaction.amount])

    return response

accountApi/adminView/templates/adminView/detail.html
{% extends 'adminView/index.html' %}

{% block body %}
<div class="container">
    <h5 class="card-text">User Name: {{ user.name }}</h5>
</div>
<br/>
<br/>
    <div class="row">
        <div class="col-md-6">
            <h4>Accounts</h4>
            <table class="table table-striped table-bordered table-smaller-font center">
                <thead>
                    <tr>
                        <th class="center">ID</th>
                        <th class="center">USER ID</th>
                        <th class="center">TYPE</th>
                        <th class="center">AMOUNT</th>
                    </tr>
                </thead>
                <tbody>
                {% for account in accounts %}
                    <tr>
                        <td>{{ account.id }}</td>
                        <td>{{ account.user }}</td>
                        <td>{{ account.type }}</td>
                        <td>{{ account.amount }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h4>Transactions</h4>
            <table class="table table-striped table-bordered table-smaller-font center">
                <thead>
                    <tr>
                        <th class="center">ID</th>
                        <th class="center">USER ID</th>
                        <th class="center">ACTION</th>
                        <th class="center">AMOUNT</th>
                    </tr>
                </thead>
                <tbody>
                {% for transaction in transactions %}
                    <tr>
                        <td>{{ transaction.id }}</td>
                        <td>{{ transaction.user }}</td>
                        <td>{{ transaction.action }}</td>
                        <td>{{ transaction.amount }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        </div>
    </div>
    {% if accounts or transactions %}
        <a href="{% url 'adminView:csv' user.id %}" class="btn btn-primary">Download CSV</a>
    {% endif %}
{% endblock %}

accountApi/adminView/templates/adminView/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <form action="{% url 'adminView:detail'  %}" method="post">
        {% csrf_token %}
          <input type="text" readonly class="form-control-plaintext" value="e.g Enter User Id"><br/>
          <input type="input" class="form-control" name="userId" >
        <br/>
        <button type="submit" class="btn btn-primary mb-2">Search</button>
      </form>
      <br/>
      <br/>
    {% block body %}
    {% endblock %}
</body>
</html>